spring:
  mail:
    host: smtp.163.com
    username: 
    password:
    port: 25
  servlet:
    multipart:
      # maxFileSize 单个数据大小
      max-file-size: 10MB
      # maxRequestSize 是总数据大小
      max-request-size: 100MB



